POST http://localhost:8000/events/add-cart/LL0017/
#POST https://shs.losa.cz/events/add-cart/Z0002/
#POST https://bazarek.webh.cz/events/add-cart/Z0002/
Accept: application/json
Authorization: Token 1bdd79b833660282050a9453678e74f5b3d0ca0d

[
{
"seller":4,
"order": 1,
"price":50
},
{
"seller":8,
"order": 2,
"price":120
},
{
"seller":13,
"order": 3,
"price":70
},
{
"seller":4,
"order": 4,
"price":35
}
]