# Generated by Django 4.2 on 2023-09-15 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0002_alter_cart_options_alter_eventseller_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='eventseller',
            unique_together={('event', 'seller')},
        ),
        migrations.RemoveField(
            model_name='seller',
            name='default_number',
        ),
        migrations.AddField(
            model_name='eventseller',
            name='identifier',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Seller number (default setting)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seller',
            name='default_identifier',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Seller number (default setting)'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='is_no_fees',
            field=models.BooleanField(default=False, verbose_name='No fees'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='total_fees',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total Fees'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='total_sales_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total sales amount'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='total_sold_items',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Total sold items'),
        ),
        migrations.AlterUniqueTogether(
            name='eventseller',
            unique_together={('event', 'seller')},
        ),
    ]
