# Generated by Django 4.2 on 2023-10-19 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0004_alter_cart_options_alter_cart_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ['event', 'identifier'], 'verbose_name': 'Košík', 'verbose_name_plural': 'Košíky'},
        ),
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['-date'], 'verbose_name': 'Událost', 'verbose_name_plural': 'Události'},
        ),
        migrations.AlterModelOptions(
            name='eventseller',
            options={'ordering': ['event', 'seller'], 'verbose_name': 'Událost - prodejce', 'verbose_name_plural': 'Událost - prodejci'},
        ),
        migrations.AlterModelOptions(
            name='eventuser',
            options={'ordering': ['event', 'user'], 'verbose_name': 'Událost - Uživatel', 'verbose_name_plural': 'Událost - uživatelé'},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['cart', 'event_seller', 'price'], 'verbose_name': 'Položka', 'verbose_name_plural': 'Položky'},
        ),
        migrations.AlterModelOptions(
            name='seller',
            options={'ordering': ['nickname'], 'verbose_name': 'Prodejce', 'verbose_name_plural': 'Prodejci'},
        ),
        migrations.AddField(
            model_name='cart',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Cart checked'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='identifier',
            field=models.CharField(max_length=128, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='x_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(verbose_name='datum'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fee_value_default',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Pevné poplatky výchozí hodnota'),
        ),
        migrations.AlterField(
            model_name='event',
            name='fee_value_percentage',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Procentuální poplatky výchozí hodnota'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_closed',
            field=models.BooleanField(default=False, verbose_name='Zavřeno'),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(max_length=128, verbose_name='název'),
        ),
        migrations.AlterField(
            model_name='event',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Poznámky'),
        ),
        migrations.AlterField(
            model_name='event',
            name='x_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='bazaar.event'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='identifier',
            field=models.PositiveSmallIntegerField(verbose_name='Identifikátor prodejce'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='is_no_fees',
            field=models.BooleanField(default=False, verbose_name='Bez poplatků'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='bazaar.seller'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='total_fees',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Poplatky celkem'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='total_sales_amount',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Celková hodnota prodeje'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='total_sold_items',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Počet prodaných položek'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='x_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='eventuser',
            name='x_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='item',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='bazaar.cart', verbose_name='Košík'),
        ),
        migrations.AlterField(
            model_name='item',
            name='event_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_seller', to='bazaar.eventseller'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Cena'),
        ),
        migrations.AlterField(
            model_name='item',
            name='size',
            field=models.CharField(max_length=32, verbose_name='Velikost'),
        ),
        migrations.AlterField(
            model_name='item',
            name='x_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Vytvořeno'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='default_identifier',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Číslo prodejce (výchozí nastavení)'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Aktivní'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='is_no_fees_default',
            field=models.BooleanField(default=False, verbose_name='Bez poplatků (výchozí nastavení)'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Název'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='nickname',
            field=models.CharField(max_length=128, unique=True, verbose_name='Uživatelské jméno'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Poznámky'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='phone',
            field=models.CharField(blank=True, max_length=128, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='seller',
            name='x_created',
            field=models.DateTimeField(auto_now=True, verbose_name='Vytvořeno'),
        ),
    ]
