# Generated by Django 4.2 on 2024-03-25 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazaar', '0006_alter_item_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='short_name',
            field=models.CharField(default='', max_length=16, verbose_name='short name'),
            preserve_default=False,
        ),
    ]
