# Generated by Django 4.2 on 2024-04-28 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazaar', '0008_alter_seller_options_item_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventseller',
            options={'ordering': ['event', 'identifier'], 'verbose_name': 'Událost - prodejce', 'verbose_name_plural': 'Událost - prodejci'},
        ),
        migrations.CreateModel(
            name='EashoUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(blank=True, max_length=8, verbose_name='Prefix')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
