# Generated by Django 4.2 on 2024-08-18 10:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bazaar', '0010_alter_eashouser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bazaar.event', verbose_name='Událost'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='is_checked',
            field=models.BooleanField(default=False, verbose_name='Košík zkontrolován'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carts_user', to=settings.AUTH_USER_MODEL, verbose_name='Uživatel'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_name',
            field=models.CharField(max_length=16, verbose_name='přezdívka'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event', to='bazaar.event', verbose_name='Událost'),
        ),
        migrations.AlterField(
            model_name='eventseller',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='bazaar.seller', verbose_name='Prodejce'),
        ),
        migrations.AlterField(
            model_name='item',
            name='event_seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='event_seller', to='bazaar.eventseller', verbose_name='Prodejce'),
        ),
    ]
